# Generated by Django 4.1.7 on 2023-06-13 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MathsAdventurer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='users_watching',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=1)),
                ('placement', models.IntegerField(blank=True)),
                ('score', models.IntegerField(blank=True)),
                ('status', models.CharField(choices=[('Not attempted yet', 'Notyet'), ('Missed milestone', 'Missed'), ('Achieved milestone', 'Achieved')], default='Not attempted yet', max_length=30)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MathsAdventurer.competition')),
            ],
        ),
    ]
