# Generated by Django 4.1.7 on 2023-06-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MathsAdventurer', '0004_difficulty_topic_alter_resource_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='colour',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
