# Generated by Django 4.1.7 on 2023-06-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MathsAdventurer', '0006_alter_milestone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not attempted yet'), (1, 'Missed milestone'), (2, 'Achieved milestone')], default=0, max_length=30),
        ),
    ]
