# Generated by Django 4.1.7 on 2023-06-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MathsAdventurer', '0007_alter_competition_name_alter_milestone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='placement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
