# Generated by Django 4.1.7 on 2023-06-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MathsAdventurer', '0008_alter_milestone_placement_alter_milestone_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
