# Generated by Django 4.1.7 on 2023-06-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MathsAdventurer', '0009_milestone_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not attempted yet'), (1, 'Missed milestone'), (2, 'Achieved milestone')], default=0),
        ),
    ]
