# Generated by Django 4.1.7 on 2023-06-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MathsAdventurer', '0010_alter_milestone_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('round', models.IntegerField(default=1)),
                ('written', models.CharField(choices=[('online', 'Online'), ('at another location', 'Campus'), ('at your own school', 'School')], default='online', max_length=30)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='MathsAdventurer.competition')),
            ],
        ),
    ]
