# Generated by Django 4.1.7 on 2023-06-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MathsAdventurer', '0011_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='written',
            field=models.CharField(choices=[('online', 'Online'), ('at central location', 'Campus'), ('at your own school', 'School')], default='online', max_length=30),
        ),
    ]
